
# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.bkav.lk: DEBUG

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.2.100:3306/lichkham?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: lichkham
    password: LK1234a@
    hikari:
      auto-commit: false
      maximum-pool-size: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: demo
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: evotekvlands@gmail.com
    password: Evotek@1234
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.2.100
    port: 6379
    cache-name:
      jwt: CurrentJwt

server:
  port: 8080
#    servlet:
#        session:
#            cookie:
#                domain: vlands.vn
#                http-only: true
#                path: /
security:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: NThlODQ0NTBjYjNlZjEyMGMzYzU4YjM1MTJmNWVkZGIzMzRmZjMxMTUwM2VhZDA2NDA2YTZhMTI4OTQxNmM3N2MzODE5MDQwYzc0YTBiMDU1ZTU5ODdkODgyYTllNTdkZDJkMDg3NWYxYTFhNmRmNGE5YjkzMTczYTQwMGJlNDc=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

application:
  folderUpload: 'E:\\FILE_BKLK\\Storage'
  template: 'excel_template'

cache:
  localIp: '127.0.0.1'
  remoteIp: '127.0.0.1'
  time-to-live-seconds: 3600
  backup-count: 1
  management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
    enabled: false
    update-interval: 3
    url: http://192.168.2.100:8180/hazelcast-mancenter

firebase:
  fcm-account-service: firebase/fcm.json

#  * "0 0 * * * *" = the top of every hour of every day.
#  * "*/10 * * * * *" = every ten seconds.
#  * "0 0 8-10 * * *" = 8, 9 and 10 o'clock of every day.
#  * "0 0 8,10 * * *" = 8 and 10 o'clock of every day.
#  * "0 0/30 8-10 * * *" = 8:00, 8:30, 9:00, 9:30 and 10 o'clock every day.
#  * "0 0 9-17 * * MON-FRI" = on the hour nine-to-five weekdays
#  * "0 0 0 25 12 ?" = every Christmas Day at midnight
scheduling:
  doctor-appointment:
    time-cron: '-'
    enable: false
  notification-reminder:
    time-cron: '0 0/30 6-20 * * *'
    enable: false
  medication-reminder:
    time-cron: '0 */1 6-22 * * *'
    enable: false
  feedback-reminder:
    time-cron: '0 0 */30 * * *'
    enable: false
  appointment-cancel-log:
    check-blocked:
      time-cron: '0 0 0 * * *'
      enable: false
    refresh-daily:
      time-cron: '0 0 0 * * *'
      enable: false
    refresh-weekly:
      time-cron: '0 0 0 * * MON'
      enable: false
  notification-cls-kq:
    time-cron: '0 0 * * * *'
  doctor-appointment-reminder-notification:
    time-cron: '-'
    enable: false
    time-default: '480'
  doctor-appointment-active-pending-config:
#    time-cron: '0 0 * * * *'
    time-cron: '0 0 * * * *'
    enable: false
  system-notification:
    time-cron: '0 0 0 * * *'

his:
  host: 'http://localhost:8080'
  doctor_list_url: '/api/public/danhsachbacsykham'
  patient_check_url: '/api/public/benhnhan/'
  medical_result_url: '/api/public/ketquakham/'
  appointment_code_check_url: '/api/public/makham/'
  patient_phone_url: '/api/public/benhnhan/makham/{his_makham}/sodienthoai'

social-insurance:
  host: 'http://localhost:8080'
  insurance_code_check_url: '/api/public/baohiemyte/'

# Tích hợp VNPay
vnpay:
  payUrl: 'http://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
  callbackUrl: 'http://localhost:4200/appointment'
  apiUrl: 'http://sandbox.vnpayment.vn/merchant_webapi/merchant.html'
  hashSecret: 'YMJOCBLEXDBWIQXYCYYTBVLGVSQZBOCV'
  tmnCode: 'TNVN0001'

otp:
  #  the verify code's length
  num-digits: 4
  session-duration: 60
  message-template: 'Your code is %s'
  turn-on-otp-default: true
  code: '1111'
  provider:
    telesign:
      customer-id: "AC8FF6E1-206E-4EC5-9F27-CE8148D62DD2"
      api-key: "1B5Rqig0SxO8gGTIndaPwpjpgbcqOsXQNUS9jwdNiSTVkEnQVKhF9ShNStE396DIMKfL7eFaq+TvJkJEo2uhHA=="

feedback:
  change_state_day_config: 1

appointment:
  config:
    max-day-pending: 30

ybi-sso:
  client-id: "e76Muf74vAAcNfSj4NToqXl30Uga"
  client-secret: "72I7JCr5Ook4lPPQv8lWw_tbOQ8a"
  api-get-token: "https://login.yenbai.gov.vn/oauth2/token"
  api-revoke-token: "https://login.yenbai.gov.vn/oauth2/revoke"
  api-logout-oidc: "https://login.yenbai.gov.vn/oidc/logout"
  api-get-user-info: "https://login.yenbai.gov.vn/oauth2/userinfo"
  redirect-uri: "http://lichkham.evotek.vn/api/oauth2/ybi/callback"
  redirect-header-value: "http://localhost:4200/login?"
google-map:
  api-key: "AIzaSyClHasepzubogG3tATPPskYH7b5p5FY1tI"
  url-geocode: "https://maps.googleapis.com/maps/api/geocode/json"
